[package]
name = "nebula"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "nebula"
path = "src/main.rs"

[dependencies]
nebula-core = { workspace = true }
nebula-daemon = { workspace = true }
nebula-tui = { workspace = true }
anyhow = { workspace = true }
clap = { version = "4", features = ["derive", "wrap_help"] }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
tempfile = "3"
tokio = { workspace = true, features = ["test-util"] }
serde_json = { workspace = true }
portable-pty = "0.9"
vt100 = "0.16"
